name: checks

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run Ruff
        run: |
          ruff check $(git ls-files '*.py')
          ruff format --check $(git ls-files '*.py')

      - name: Run Mypy
        run: |
          mypy src/

      - name: Run Pytest
        run: |
          pytest
